[versions]
spek = "2.0.19"

[libraries]
awaitility = "org.awaitility:awaitility-kotlin:4.3.0"
json = "org.json:json:20250517"
spek-dsl-jvm = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
spek-runner-junit5 = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:7.0.12"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.0.21"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:2.0.0"
publishOnCentral = "org.danilopianini.publish-on-central:7.0.4"
